### PR TITLE
Fail gracefully when visualizing  a calculation with no orbitals

### LINKED ISSUE #102: Make sure that result.structure.show() is the right structure
In the case of ANI, the geometry optimization does not create orbitals, but in the general case we might just want to look at the structure from an optimization or other calculation. Right now I must do something such as:
```
ani_optimized_id = result.optimized_geometry_id
mol.structure.show(geometry_id=ani_optimized_id)
```
When I want to be able to call `result.structure.show()` more naturally.

### PR DESCRIPTION
**Pull request by alesgenova**
Fixes #102

### CODE REVIEW

**Comment by cryos** [comment]
Does structure already show the optimized structure from the calculation? This addresses part of it, failing more gracefully, but doesn't fully address it unless you can confirm that we can show the output of an optimization with result.structure. In my testing I couldn't just look at the structure, and your commit message seems to say it will just fail gracefully.

**Comment by alesgenova** [comment]
As I was developing this PR, it looked like `result.structure.show()` had been working already, so I proceeded to fix the fact that if a user calls `result.orbitals.show()` on a result which is missing orbitals will still be able to see the structure at least.

Finally, I just finished comparing the data in the original molecule `mol.structure.data()` and in the optimized calculation `result.structure.data()`. The positions differ as it should be expected, and the positions of the optimized calculation do match the optimized geometry.

**Comment by cryos** [comment]
Sounds good, that wasn't clear from the PR or anything written here. Thanks @alesgenova

**Review by cryos — APPROVED** [review]
See discussion in the issue, looks good to me now I know the structure being displayed is the correct one.

**Review by cjh1 — APPROVED** [review]

**Pull request merged**
