### PR TITLE
Run calculations on geometries

### PR DESCRIPTION
**Pull request by psavery**
This allows the user to specify a geometry when running a
calculation on a molecule.

Currently, the user specifies the geometry using the mongodb id.
It would probably be better to come up with a more user-friendly
identification system that maps to the mongodb ids.

Screenshot from 2019-09-04 07-29-04
Screenshot from 2019-09-04 07-41-15

Depends on [this PR](https://github.com/OpenChemistry/mongochemserver/pull/112).

### CODE REVIEW

**Comment by psavery** [comment]
Some things I can possibly work on for this PR:

- [x] Allow users to add geometries in the notebook (currently, you can only add geometries with the girder rest API).
- [x] Allow users to list geometries of molecules in some kind of table. Maybe they can also display energies if they link back to calculations.
- [x] Automatically create and upload a geometry from the output of geometry optimizations. The geometry will link back to the calculation it came from.
- [ ] Provide some kind of more user-friendly identification system for the geometries rather than the mongodb ids. This system can map to the mongodb ids. Maybe we can display the system in the table in point number 2.
- [ ] (Maybe a later goal): Add the ability to generate conformers with Open Babel, and upload all of their geometries. Should we make a new endpoint in mongochemserver for this?

**Comment by psavery** [comment]
For number 4, would it be reasonable to use truncated hashes?  Such as the first 8 characters of a sha1? Maybe the sha1 could be a string combining the mongo id with things like the provenance or the cjson.

**Comment by psavery** [comment]
The third checkbox above was completed in [this PR](https://github.com/OpenChemistry/mongochemserver/pull/112).

**Comment by psavery** [comment]
The second checkbox was also completed. An example image is attached.

Screenshot from 2019-10-17 04-13-19

**Comment by psavery** [comment]
The first checkbox is complete. Users can pass a cjson dict to `mol.add_geometry(cjson)` to add a geometry.

Screenshot from 2019-10-17 11-43-51
Screenshot from 2019-10-17 11-44-05

**Comment by psavery** [comment]
I think this is ready for review. I can work on the last two checkboxes above, but I think I need feedback before doing so.

**Comment by psavery** [comment]
The most recent commit added ways to visualize geometries in the notebooks via the following:

1. `mol.geometries.show(geometry_id=...)`. If `geometry_id` is None (default), it shows a table of the geometries. But if the geometry id is specified, it shows the specific geometry.
2. `mol.structure.show(geometry_id=...)`. If the `geometry_id` is None (default), it shows the default molecular structure (the one originally uploaded when the molecule was created). If it is specified, it shows the specific geometry.

Screenshot from 2019-10-20 14-38-50
Screenshot from 2019-10-20 14-39-47


Screenshot from 2019-10-20 14-37-07
Screenshot from 2019-10-20 14-37-47

**Review by cryos — APPROVED** [review]
This looks good, I think supporting the first 5-8 characters would be nice, maybe adding a friendly name key in the future too, but what is here looks very functional.

**Pull request merged**
