### PR TITLE
Add missing parameter to _get_job_parameters(...)

### PR DESCRIPTION
**Pull request by cjh1**

### CODE REVIEW

**Comment by cjh1** [comment]
@psavery This should resolve your issue.

**Comment by psavery** [comment]
@cjh1 Looks good, but I also get another error. Notice [here](https://github.com/OpenChemistry/openchemistrypy/pull/76/files#diff-baebcad803e7bd4bde939515825bbdb5R490) that there are 3 `%s` string formatters, but 4 arguments given to it afterwards.

**Comment by cjh1** [comment]
@psavery I fixed that up as well

**Review by psavery — APPROVED** [review]
This fixes the issues for me. I was able to run all of the calculations in all of the notebooks successfully with these fixes :slightly_smiling_face:.

**Pull request merged**
