### PR TITLE
Scaling IR experimental with largest theoretical intensity

### PR DESCRIPTION
**Pull request by muammar**
newir

These changes make overlap to look better.

### CODE REVIEW

**Comment by muammar** [comment]
JFTR, the diff with respect to `master` looks like this: 

```
diff --git a/openchemistry/_visualization.py b/openchemistry/_visualization.py
index fb30473..7fb1eaa 100644
--- a/openchemistry/_visualization.py
+++ b/openchemistry/_visualization.py
@@ -146,7 +146,8 @@ class Vibrations(Visualization):
         if experimental:
             from .api import find_spectra
             identifier = self._provider._molecule_id
-            exp_spec = find_spectra(identifier, stype='IR', source='NIST')
+            theo_intensities = self._provider.vibrations.get("intensities", None)
+            exp_spec = find_spectra(identifier, theo_intensities, stype='IR', source='NIST')
             kwargs['exp_spec'] = exp_spec
 
         return super(Vibrations, self).show(viewer=viewer, spectrum=spectrum,
diff --git a/openchemistry/api.py b/openchemistry/api.py
index d7dc52f..b31403a 100644
--- a/openchemistry/api.py
+++ b/openchemistry/api.py
@@ -184,13 +184,15 @@ def queue():
 
     return _calculation_monitor(taskflow_ids)
 
-def find_spectra(identifier, stype='IR', source='NIST'):
+def find_spectra(identifier, theo_intensities, stype='IR', source='NIST'):
     """Find spectra in source database
 
     Parameters
     ----------
     identifier : str
         Inchi string.
+    theo_intensities : list
+        List of theoretical intensities used to normalize.
     stype : str
         Type of spectrum to query.
     source : str
@@ -211,7 +213,10 @@ def find_spectra(identifier, stype='IR', source='NIST'):
     if spectrum is not None:
         frequencies = [float(w) for w in spectrum['x'][1:-1].split()]
         intensities = [float(i) for i in spectrum['y'][1:-1].split()]
-        max_intensity = max(intensities)
+        if theo_intensities is None:
+            max_intensity = max(intensities)
+        else:
+            max_intensity = max(theo_intensities)
         intensities = [i / max_intensity for i in intensities]
         spectrum = {'intensities': intensities, 'frequencies': frequencies}
 
```

**Comment by cryos** [comment]
We should just cherry pick the commit you want from a clean master, it looks like the repository was rebased at some point and changed unrelated commits.

**Comment by muammar** [comment]
> We should just cherry pick the commit you want from a clean master, it looks like the repository was rebased at some point and changed unrelated commits.

The problem is that the pull request is tried to be done against the `ir_spec` branch that was not updated for some time. Let me close this PR and try if I can change the target to `master`.

**Comment by muammar** [comment]
@cryos now #110 points to `master` instead :)

**Pull request closed without merging**
