### PR TITLE
Added basic openchemistry-client in python

### PR DESCRIPTION
**Pull request by psavery**
The client uses girder-client to make requests. Currently, it can only
list molecules.

There is a sub-command structure in place. After "openchemistry-client",
"molecules" is currently a command dealing with molecules (one other
planned command is "calculations").

After the "molecules" subcommand, the user can do things like list
molecules with an "ls" command. The full command for this is
"openchemistry-client molecules ls". It prints out a formatted
list of molecules, like the following:

```
$ openchemistry-cli molecules ls
matches: 2
limit: 25
offset: 0
results:
{
    "_id": "5d850c0293ce7a4d24143f5d",
    "inchikey": "VNWKTOKETHGBQD-UHFFFAOYSA-N",
    "properties": {
        "atomCount": 5,
        "formula": "CH4",
        "heavyAtomCount": 1,
        "mass": 16.04236,
        "spacedFormula": "C 1 H 4"
    },
    "smiles": "C"
}
{
    "_id": "5d84e88f93ce7a4d24143e31",
    "inchikey": "XLYOFNOQVPJJNP-UHFFFAOYSA-N",
    "properties": {
        "atomCount": 3,
        "formula": "H2O",
        "heavyAtomCount": 1,
        "mass": 18.01508,
        "spacedFormula": " H 2 O 1"
    },
    "smiles": "O"
}
```

Some planned features include uploading molecules from files,
listing calculations, and submitting calculations.

### CODE REVIEW

**Comment by psavery** [comment]
I wonder if I should abbreviate the name to `occlient`?

**Comment by psavery** [comment]
So, this is working now to do the following things: list molecules, upload a molecule, list calculations, submit a calculation, and download the cjson output of a calculation to a file. I tried to do things in both simple and organized ways, and I haven't added many options.

Everything is currently using the girder API directly except for submitting a calculation. Submitting a calculation uses functions from `openchemistrypy` to "fetch or submit" a calculation, so we don't have to repeat the logic. This includes a monkey patch to make `openchemistrypy` use our girder client rather than its internal one.

We are going to try to implement some of the same kinds of things in Avogadro2 using C++ and `QNetworkAccessManager`, except that we will probably be interfacing with girder directly for everything rather than using openchemistrypy, since Avogadro2 should perhaps not depend on openchemistrypy. I think this branch is a good python prototype for those things.

**Comment by cjh1** [comment]
@psavery What is the status of this?

**Comment by psavery** [comment]
I tested out this PR, and made a few small adjustments. It seems to be working, and I think it's ready for review.

**Review by cjh1 — APPROVED** [review]
LGTM

**Pull request merged**
