### PR TITLE
Allow importing a molecule by CJson

### PR DESCRIPTION
**Pull request by psavery**
Signed-off-by: Patrick Avery <patrick.avery@kitware.com>

### CODE REVIEW

**Comment by psavery** [comment]
This is all that needs to be done on the openchemistrypy side. It does work with mongochemserver (with a few caveats that we might change on mongochemserver):

1. There is a key error on mongochemserver if the version key is not named `chemicalJson` with a capital J and no spaces. In [avogadrodata](https://github.com/OpenChemistry/avogadrodata/tree/master/data), the keys are named `chemical json` with a space and a lowercase j. So I have to rename them to `chemicalJson` for it to work.
2. There is a key error if there are no bonds (such as [rutile.cjson](https://github.com/OpenChemistry/avogadrodata/blob/master/data/rutile.cjson)). Do we want to support importing crystals or molecules with no bonds?
3. Currently, mongochemserver takes the CJson, converts it into SDF format, and then back to CJson. So any metadata that is not stored in the SDF format (then put back into the final CJson) is currently lost.

**Comment by psavery** [comment]
This partially fixes part of [this mongochemserver issue](https://github.com/OpenChemistry/mongochemserver/issues/106).

**Comment by cryos** [comment]
The keyword and version were updated in the latest Avogadro too @psavery, I think we should adjust the code to be a little more forgiving as is the case in Avogadro, but version 1 of the schema switches to camel case. We shouldn't convert to/from SDF, we can take a look at that.

**Comment by psavery** [comment]
Nevermind about point number 3. It is indeed converted to sdf format, but that is only to get the inchikey, inchi, smiles, numbers of atoms, etc. The cjson the user passes in does get saved directly to the molecule's cjson [here](https://github.com/OpenChemistry/mongochemserver/blob/master/girder/molecules/server/utilities/molecules.py#L55). Its contents are, however, whitelisted [here](https://github.com/OpenChemistry/mongochemserver/blob/master/girder/molecules/server/utilities/molecules.py#L62) so that only the root keys "chemicalJson", "atoms", and "bonds" get kept.

**Comment by psavery** [comment]
I think this is ready for review. It works as far as I know.

**Review by cjh1 — APPROVED** [review]

**Pull request merged**
