### PR TITLE
Add ability to find a molecule by inchi or smiles

### PR DESCRIPTION
**Pull request by psavery**
A calculation can also be found this way

Signed-off-by: Patrick Avery <patrick.avery@kitware.com>

### CODE REVIEW

**Comment by psavery** [comment]
I copy and pasted that entire "Are we searching for a specific calculation?" code block. Perhaps I should turn it into a function or something so we don't have code duplication? Or if it doesn't matter, we can leave it...

**Comment by psavery** [comment]
So basically, if "inchi" or "smiles" or both are passed into the function, it will search using them, and not the identifier, and if it doesn't find a molecule with the inchi or smiles, an exception gets raised.

Otherwise, the function proceeds as normal if an identifier is provided and not inchi or smiles.

**Comment by psavery** [comment]
Need to make one modification...

**Comment by psavery** [comment]
I haven't tested the calculation finder, but it finds the molecule in the database fine. An exception is thrown if the molecule is not in the database.

**Comment by cjh1** [comment]
@psavery Is this ready for review now?

**Comment by psavery** [comment]
@cjh1 Yeah it is. I'm wondering if I should put the duplicated code into a function, though, so that we don't have two duplicated code blocks.

**Comment by cjh1** [comment]
@psavery Yes, that would be good, then we can merge.

**Comment by psavery** [comment]
I think it is ready for merging. I just want to test one more time.

I moved `import_structure()` up in the code when I merged with master because I put `find_structure_by_inchi_or_smiles()` in the same spot.

**Comment by psavery** [comment]
I think it works as intended. It is ready for review.

**Comment by cjh1** [comment]
@psavery Look like we have a conflict :frowning_face:

**Comment by psavery** [comment]
Yeah, it's okay. I'll fix it.

**Comment by psavery** [comment]
I fixed it, but let me test it one more time later tonight (or tomorrow morning) to make sure I merged it fine.

**Comment by psavery** [comment]
Okay, I tested it again and I think it works fine. It is ready for review. This PR partially fixes #48.

**Review by cjh1 — APPROVED** [review]

**Comment by cryos** [comment]
You know this could be a little cleverer too, any InChI starts with `InChI=`, so if we augment the function a little if import_structure sees a string starting with `InChI=` we know it should be an InChI, otherwise it should be a SMILES. We can leave the named arguments, but making the default even more intuitive would be nice.

**Pull request merged**
