### PR TITLE
Allow multiple calculations to run in one taskflow

### PR DESCRIPTION
**Pull request by psavery**
This is still a work in progress. It at least works for
running a single calculation. Multiple calculations have
not yet been attempted.

It depends on #71 and [this PR](https://github.com/OpenChemistry/mongochemdeploy/pull/77).

### CODE REVIEW

**Comment by psavery** [comment]
This currently works for chemml, and it is compatible with the sample notebook. The new function that is used is called `run_calculations`. An example looks like the following:
```
import openchemistry as oc

import matplotlib
import matplotlib.pyplot as plt
import numpy as np

structure_smiles = ['CN1CNCN(C1)c1ccc(c2c1cccc2)C1NCNCN1', 'SC1CSCC(S1)(S)c1cccnc1', 'c1ccc(nc1)c1scc(c1)c1ccnc(c1)c1ccc2c(c1)cccc2']
mols = []
results = []
for smiles in structure_smiles:
    mols.append(oc.import_structure(smiles, gen3d=False))

results = oc.run_calculations(mols, 'psavery/chemml:multi', {})

x = []
y = []
for result in results:
    x.append(result.data()['properties']['polarizability'])
    y.append(result.data()['properties']['refractiveIndex'])

fig, ax = plt.subplots()
ax.plot(x, y, 'ro')
ax.set(xlabel='polarizability', ylabel='refractive index', title='Machine learning...')
ax.grid()
```
Screenshot from 2019-05-27 11-46-10

**Comment by psavery** [comment]
I tried this out with psi4 as well. It still works fine using the current notebook setup, and also running multiple calculations (as can be seen below):

Screenshot from 2019-05-27 20-12-26
Screenshot from 2019-05-27 20-13-21

**Comment by psavery** [comment]
Although one thing to note: I should probably but in a check somewhere when running psi4 and nwchem calculations to make sure there are 3D coordinates (and maybe generate them if they do not exist). Otherwise we will get some error I'm sure.

**Comment by psavery** [comment]
I tested nwchem with code similar to the psi4 example above, and it seems to work fine as well.

**Comment by psavery** [comment]
This now submits a REST request to start generating 3D coordinates if the molecule doesn't have 3D coordinates and the user asks it to perform a calculation that requires 3D coordinates (currently required for psi4 and nwchem calculations). It asks the user to try again soon.

This seems to work fine as intended, but it currently communicates the information to the user via an exception, which may not be the best way (see attached).

Screenshot from 2019-06-12 11-48-04

**Comment by cjh1** [comment]
Looks like we have some conflicts to resolve

**Comment by psavery** [comment]
I can take a look.

**Review by cjh1 — APPROVED** [review]

**Pull request merged**
